# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main","lab-04" ]
  pull_request:
    branches: [ "main","lab-04" ]

env:
  DATABASE_URL: postgres://bbdkykjzitfeok:3b3dd7d9d039db73241f2ec108002ae09034e6d15706845ac619d3f508c8cd7e@ec2-52-30-75-37.eu-west-1.compute.amazonaws.com:5432/d8u4svkpnb7m9u

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
